name: news_app
description: A simple news application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  http: ^1.2.0
  google_fonts: ^6.2.1
  jiffy: ^6.3.2
  loadmore: ^2.1.0
  fluttertoast: ^8.2.2
  skeletons: ^0.0.3
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.2.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/
